name: "slack message"
author: "kyoncy"
description: "post message to slack"
branding:
  icon: slack
  color: green
inputs:
  token:
    description: "GitHub token for use by this action."
    required: false
    default: ${{ github.token }}
  message:
    description: "Message"
    required: false
    default: |
      Thank you for opening the issue!
runs:
  using: "node12"
  main: "dist/index.js"
