name: post message to slack

on: push

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          slack_username: "Github Actions notification"
          slack_icon_url: "https://avatars0.githubusercontent.com/u/44036562?s=200&v=4"
          slack_color: "good"
          slack_title: ":tada: Success"
